version: '4'
services:
  mysql:
    image: mysql:8.0.41-debian
    container_name: mysql-file-service
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3326:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql